spring:
  profiles: db
  datasource:
    url: jdbc:jtds:sqlserver://10.182.70.12/audit_log;useNTLMv2=true;domain=cwopa;integratedSecurity=true
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    initialize: true
